<?php
/**
 * @file
 * Module to supply footer icons for ASC Sites.
 */

/**
 * @defgroup asc_footer
 * Module to supple field to add OPIC image.
 *
 * And finally, our module defines the widet in
 * opic_field_widget_info() and field_example_field_widget_form().
 * The widget is the form element used to receive input from the user
 * when the field is being populated.
 *
 * @see field_types
 * @see field
 */

/**
 * Implements hook_menu().
 *
 * Provides a simple user interface that tells the developer where to go.
 */
function asc_breadcrumbs_preprocess_page($vars) {
  if (!$vars['is_front']) {
    $breadcrumb[] = l(t('Home'), NULL);
    $sections = array(
      'asc_news' => array(
        'name' => 'News',
        'path' => 'news',
      ),
      'asc_event' => array(
        'name' => 'Events',
        'path' => 'events',
      ),
      'asc_people' => array(
        'name' => 'People',
        'path' => 'directory',
      ),
      'asc_blog' => array(
        'name' => variable_get('asc_blog_name'),
        'path' => 'blog',
      ),
    );
    $type = (isset($vars['node']->type) ? $vars['node']->type : '');

    (isset($type) && array_key_exists($type, $sections)) ? ($breadcrumb[] = l($sections[$type]['name'], $sections[$type]['path'])) : '';

    $breadcrumb[] = l(drupal_get_title(), request_path());
    drupal_set_breadcrumb($breadcrumb);
  }
}
