<?php
/**
 * @file
 * Module to supply breadcrumbs for ASC Sites.
 */

/**
 * @defgroup asc_breadcrumbs
 * Simple module to override breadcrumbs for ASC sites..
 *
 */

/**
 * Implements hook_preprocess_page().
 *
 * Create breadcrumbs for our content types and set the trail; otherwise, use
 * the title as the second trail item.
 *
 */
function asc_breadcrumbs_preprocess_page($vars) {
  if (!$vars['is_front']) {
    $breadcrumb[] = l(t('Home'), NULL);
    $sections = array(
      'asc_news' => array(
        'name' => 'News',
        'path' => 'news',
      ),
      'asc_announcement' => array(
        'name' => 'Announcements',
        'path' => 'announcements',
      ),
      'asc_event' => array(
        'name' => 'Events',
        'path' => 'events',
      ),
      'asc_exhibition' => array(
        'name' => 'Exhibitions',
        'path' => 'exhibitions',
      ),
      'asc_design' => array(
        'name' => 'Designs',
        'path' => 'designs',
      ),
      'asc_people' => array(
        'name' => 'People',
        'path' => 'directory',
      ),
      'asc_blog' => array(
        'name' => 'Blog',
        'path' => 'blog',
      ),
      'asc_workshop_course' => array(
        'name' => 'Courses',
        'path' => 'courses',
      ),
      'asc_workshop' => array(
        'name' => 'Workshops',
        'path' => 'upcoming-workshops',
      ),
      'asc_courses' => array(
        'name' => 'Courses',
        'path' => 'courses',
      ),
      'publications' => array(
        'name' => 'Publications',
        'path' => 'publications',
      ),
      'product_page' => array(
        'name' => 'Store',
        'path' => 'store',
      ),
    );

    $type = (isset($vars['node']->type) ? $vars['node']->type : '');

    if (isset($type) && array_key_exists($type, $sections)) {
      $breadcrumb[] = l($sections[$type]['name'], $sections[$type]['path']);
			
	    $noemtitle = preg_replace('/<\/?em>/', '', drupal_get_title());
	    $breadcrumb[] = l($noemtitle, request_path());
			drupal_set_breadcrumb($breadcrumb);
    }
		else {
			$breadcrumb = menu_get_active_breadcrumb();
	    $noemtitle = preg_replace('/<\/?em>/', '', drupal_get_title());
	    $breadcrumb[] = l($noemtitle, request_path());
			drupal_set_breadcrumb($breadcrumb);
		}
  }

}
