<?php
/**
 * @file
 * Module to supply breadcrumbs for ASC Sites.
 */

/**
 * @defgroup asc_breadcrumbs
 * Simple module to override breadcrumbs for ASC sites..
 *
 */

/**
 * Implements hook_preprocess_page().
 *
 * Create breadcrumbs for our content types and set the trail; otherwise, use
 * the title as the second trail item.
 *
 */
function asc_breadcrumbs_preprocess_page($vars) {
  if (!$vars['is_front']) {
    $sections = array(
      'asc_news' => array(
        'name' => 'News',
        'path' => 'news',
      ),
      'asc_event' => array(
        'name' => 'Events',
        'path' => 'events',
      ),
      'asc_people' => array(
        'name' => 'People',
        'path' => 'directory',
      ),
      'asc_blog' => array(
        'name' => variable_get('asc_blog_name'),
        'path' => 'blog',
      ),
    );

    $type = (isset($vars['node']->type) ? $vars['node']->type : '');

    if (isset($type) && array_key_exists($type, $sections)) {
      $breadcrumb[] = l(t('Home'), NULL);
      $breadcrumb[] = l($sections[$type]['name'], $sections[$type]['path']);
      $noemtitle = preg_replace('/<\/?em>/', '', drupal_get_title());
      $breadcrumb[] = l($noemtitle, request_path());
      drupal_set_breadcrumb($breadcrumb);
    }

  }
}
